# Generated by Django 4.2.27 on 2026-09-13 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('completed', 'Successful'), ('pending', 'Pending'), ('declined', 'Failed')], default='completed', max_length=10)),
                ('category', models.CharField(choices=[('internal', 'Internal transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('bill', 'Bill payment'), ('external', 'External / interbank'), ('card', 'Card purchase'), ('admin', 'Admin adjustment')], default='internal', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Bank admin')], default='customer', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=300)),
                ('tone', models.CharField(default='teal', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveTransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Transaction submitted'), ('network', 'Checking network route'), ('verification', 'Verifying with issuer'), ('pending', 'Held for manual review'), ('issue', 'Network issue detected'), ('flagged', 'Verification issue — hold'), ('completed', 'Completed')], default='completed', max_length=14)),
                ('category', models.CharField(choices=[('internal', 'Internal transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('bill', 'Bill payment'), ('external', 'External / interbank'), ('card', 'Card purchase'), ('admin', 'Admin adjustment')], default='internal', max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalTransferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('recipient_account_number', models.CharField(max_length=32)),
                ('recipient_name', models.CharField(max_length=150)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_detail', to='banking.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fixed_rate', models.DecimalField(decimal_places=2, default=8.5, help_text='Annual %, e.g. 8.50', max_digits=4)),
                ('fixed_maturity', models.DateField(blank=True, null=True)),
                ('fixed_term_months', models.PositiveIntegerField(default=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
