# Generated by Django 4.2.27 on 2026-10-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetransactionstatus',
            name='category',
            field=models.CharField(choices=[('internal', 'Internal transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('bill', 'Bill payment'), ('external', 'External / interbank'), ('card', 'Card purchase'), ('admin', 'Credit Adjustment')], default='internal', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('internal', 'Internal transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('bill', 'Bill payment'), ('external', 'External / interbank'), ('card', 'Card purchase'), ('admin', 'Credit Adjustment')], default='internal', max_length=12),
        ),
    ]
